### ISSUE TITLE
Code to connect to MongoDB from current app.

### ISSUE THREAD

**Issue by ShelterApp** [ShelterApp/OutreachMobile#5]
We need a boilerplate code in current app to connect/talk to MongoDB collections for performing basic CRUD (Create, Read, Update, Delete) operations on data.

- Adding an organization
- Updating an org
- Adding a Supply item
- Adding a volunteer.

Code should also do bulk insert/ bulk delete/ bulk update.

Depends on outcome of #7

**Comment by prabhushrikant** [comment]
Not needed anymore since we will be using mongodb realm , so bunch of backend tasks would take care of it.
